name: Set environment variable
description:
  Set environment variables for use in other actions.
inputs:
  key:
    description: The name of the environment variable to set.
    required: true
  value:
    description: The value of the environment variable to set.
    required: true
runs:
  using: composite
  steps:
    - name: Set environment variable
      run: echo "${{ inputs.key }}=${{ inputs.value }}" >> $GITHUB_ENV
      shell: bash
