name: Windows Release

on:
  push:
    branches: [ "master" ]
    paths:
      - .github/workflows/windows-release.yml
  workflow_dispatch:

env:
  ARCHITECTURE: windows-x64

jobs:
  build-windows-release:
    defaults:
      run:
        shell: bash
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.3"
          channel: 'stable'

      - name: Start Windows release build ${{ github.ref_name }}
        run: flutter build windows

      - name: Install Inno-setup ChineseSimplified.isl
        run: |
          curl -LJO \
          https://raw.github.com/jrsoftware/issrc/main/Files/Languages/Unofficial/ChineseSimplified.isl
          cp ChineseSimplified.isl 'C:\Program Files (x86)\Inno Setup 6\Languages\'

      - name: Inno-setup package installer
        run: |
          sed -i '1i\#define MyAppId "7426D8CB-93E6-4AA9-9D92-E9A20608C5E9"' setup.iss
          sed -i '3i\#define MyAppVersion "1.0.0"' setup.iss
          iscc "setup.iss"

      - name: Upload Windows release to artifacts
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: mysetup
          compression-level: 9
          path: Output/mysetup.exe