name: Windows Release

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  ARCHITECTURE: windows-x64

jobs:
  build-windows-release:
    defaults:
      run:
        shell: bash
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.3"
          channel: 'stable'
          cache: true

      - name: Start Windows release build ${{ github.ref_name }}
        run: flutter build windows

      - name: Install Inno-setup ChineseSimplified.isl
        run: |
          curl -o ChineseSimplified.isl \
          https://github.com/kira-96/Inno-Setup-Chinese-Simplified-Translation/blob/main/ChineseSimplified.isl
          cp ChineseSimplified.isl "C:\Program Files (x86)\Inno Setup 6\Languages\ChineseSimplified.isl"
          ls -la "C:\Program Files (x86)\Inno Setup 6\"
          ls -la "C:\Program Files (x86)\Inno Setup 6\Languages\"

      - name: Inno-setup package installer
        run: |
          iscc "SetupScript.iss"

      - name: Upload Windows release to artifacts
        uses: actions/upload-artifact@v4
        with:
          retention-days: 7
          name: mysetup
          path: mysetup.exe